### ISSUE TITLE
Getting Error with Glyphs 3.2

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/System7Shadow#2]
in 3179:

```py
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 622, in process_
  File "plugin.py", line 196, in filter
    mergeLayer.applyTransform(shiftMatrix)
  File "GlyphsApp/GlyphsApp/__init__.py", line 8800, in __GSLayer_applyTransform__
NameError: name 'NSAffineTransformStruct' is not defined
```

Glyphs Python 3.9.1

in 3180 it works, but causes #1 
in 3151 it works, but causes #1 

@schriftgestalt

**Comment by Mark2Mark** [comment]
as it works in 3080, I close it right away
